name: C Build and test
on:
 push:
  branches: main
 pull_request:
  branches: main

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    -name: checkout repository
     uses: actions/checkout@v4

    -name: install build tools
     uses: sudo apt-get update && sudo apt-get install -y build-essential

    -name: Build program
     uses: make

    -name: Run tests
     uses: make test

    -name: Upload binary artifact
     uses: actions/upload-artifact@v4

     with:
       name: hello-binary
       path: hello
